2024-02-13 19:13:14,496:logger:An unexpected error occurred while extracting text from image: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

2024-02-13 19:13:59,200:logger:An unexpected error occurred while extracting text from image: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

2024-02-13 19:14:00,674:logger:An unexpected error occurred while extracting text from image: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

2024-02-13 19:14:59,394:logger:An unexpected error occurred while extracting text from image: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

2024-02-13 19:19:37,323:logger:An unexpected error occurred while plotting dominant colors: RGBA values should be within 0-1 range
2024-02-13 19:22:42,183:logger:An unexpected error occurred while plotting dominant colors: unsupported operand type(s) for /: 'tuple' and 'int'
2024-02-13 19:22:50,845:logger:An unexpected error occurred while plotting dominant colors: unsupported operand type(s) for /: 'tuple' and 'int'
2024-02-15 02:42:04,227:logger:Error while generating image: Error code: 401 - {'error': {'code': 'invalid_api_key', 'message': 'Incorrect API key provided: sk-PZtej***************************************XzzH. You can find your API key at https://platform.openai.com/account/api-keys.', 'param': None, 'type': 'invalid_request_error'}}
2024-02-15 02:43:06,116:logger:Error while generating image: Error code: 401 - {'error': {'code': 'invalid_api_key', 'message': 'Incorrect API key provided: sk-PZtej***************************************XzzH. You can find your API key at https://platform.openai.com/account/api-keys.', 'param': None, 'type': 'invalid_request_error'}}
2024-02-15 02:43:11,685:logger:Error while generating image: Error code: 401 - {'error': {'code': 'invalid_api_key', 'message': 'Incorrect API key provided: sk-PZtej***************************************XzzH. You can find your API key at https://platform.openai.com/account/api-keys.', 'param': None, 'type': 'invalid_request_error'}}
2024-02-15 16:59:49,960:logger:Error downloading image from https://oaidalleapiprodscus.blob.core.windows.net/private/org-meifkcFj5A9IjlflOqxcVZBe/user-ZPTxrE5Z3of20YjzdGT5LsFj/img-CqV7n20zPyVdzSR9X4kWKUlg.png?st=2024-02-15T11%3A29%3A16Z&se=2024-02-15T13%3A29%3A16Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-02-15T02%3A27%3A42Z&ske=2024-02-16T02%3A27%3A42Z&sks=b&skv=2021-08-06&sig=Ea7OAFAk%2BiIlwLVgxb%2BD3O6EVL75FOoIUZqyPwd5hDQ%3D: 403 Client Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. for url: https://oaidalleapiprodscus.blob.core.windows.net/private/org-meifkcFj5A9IjlflOqxcVZBe/user-ZPTxrE5Z3of20YjzdGT5LsFj/img-CqV7n20zPyVdzSR9X4kWKUlg.png?st=2024-02-15T11%3A29%3A16Z&se=2024-02-15T13%3A29%3A16Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-02-15T02%3A27%3A42Z&ske=2024-02-16T02%3A27%3A42Z&sks=b&skv=2021-08-06&sig=Ea7OAFAk%2BiIlwLVgxb%2BD3O6EVL75FOoIUZqyPwd5hDQ%3D
2024-02-16 15:46:32,093:logger:An unexpected error occurred: module 'PIL.Image' has no attribute 'ANTIALIAS'
2024-02-16 16:16:01,196:logger:Error while detecting objects and info: int() argument must be a string, a bytes-like object or a number, not 'NDArray'
2024-02-16 16:18:14,587:logger:Error while detecting objects and info: int() argument must be a string, a bytes-like object or a number, not 'NDArray'
2024-02-16 16:20:38,652:logger:Error while detecting objects and info: int() argument must be a string, a bytes-like object or a number, not 'NDArray'
2024-02-16 16:23:00,376:logger:Error while detecting objects and info: int() argument must be a string, a bytes-like object or a number, not 'NDArray'
2024-02-16 16:37:16,009:logger:Error while detecting objects and info: index 1 is out of bounds for axis 0 with size 1
2024-02-16 17:10:46,290:logger:An unexpected error occurred: 'str' object has no attribute 'read'
